export enum OPEN_BILL_ERROR {
    FAILED_TO_CREATE_OPEN_BILL_ERROR = "FAILED_TO_CREATE_OPEN_BILL_ERROR",
    FAILED_TO_READ_OPEN_BILLS_ERROR = "FAILED_TO_READ_OPEN_BILLS_ERROR"
}

export enum CLOSE_BILL_ERROR {
    FAILED_TO_CLOSE_BILL_ERROR = "FAILED_TO_CLOSE_BILL_ERROR",
    INVALID_PAYLOAD_ERROR = "INVALID_PAYLOAD_ERROR"
}