export enum CREATE_BILL_ITEM_ERRORS {
    INVALID_PAYLOAD_ERROR = "INVALID_PAYLOAD_ERROR",
    FAILED_TO_CREATE_BILL_ITEM_ERROR = "FAILED_TO_CREATE_BILL_ITEM_ERROR",
    FAILED_TO_UPDATE_KOT = "FAILED_TO_UPDATE_KOT"
}

export enum UPDATE_BILL_ITEM_ERROR {
    INVALID_PAYLOAD_ERROR = "INVALID_PAYLOAD_ERROR",
    FAILED_TO_UPDATE_BILL_ITEM_ERROR = "FAILED_TO_UPDATE_BILL_ITEM_ERROR"
}