export enum ExpenseAPIErrors {
    CREATE_EXPENSE_SERVER_ERR = "CREATE_EXPENSE_SERVER_ERR",
    CREATE_EXPENSE_INVALID_PAYLOAD = "CREATE_EXPENSE_INVALID_PAYLOAD",
    GET_EXPENSE_SERVER_ERROR = "GET_EXPENSE_SERVER_ERROR",
    GET_EXPENSE_START_AND_END_REQUIRED_ERR = "GET_EXPENSE_START_AND_END_REQUIRED_ERR"
}