export enum ITEM_CAT_ERRORS {
    ERROR_FETCHING_CATS = "ERROR_FETCHING_CATS",
    ERROR_CREATING_CAT = "ERROR_CREATING_CAT"
}

export enum ITEM_CREATE_ERRORS {
    ERROR_CREATING_ITEM = "ERROR_CREATING_ITEM"
}