export enum OTP_ERRORS {
    TRANSPORT_ERROR = "TRANSPORT_ERROR",
    INVALID_EMPID_PIN_MOBILE_COMB_ERROR = "INVALID_EMPID_PIN_MOBILE_COMB_ERROR",
    INVALID_PAYLOAD_ERROR = "INVALID_PAYLOAD_ERROR",
    OTP_REQUEST_ERROR = "OTP_REQUEST_ERROR"
} 